"""Reporting & misc-stat endpoints — business stats, report generation, stubs.

Extracted from main.py. Self-contained, no shared app state. (Dead helpers
_REPORT_TEMPLATE / _build_report_body were dropped — they were never called.)
"""

import os
import subprocess

from fastapi import APIRouter, Request

router = APIRouter(tags=["reports"])

REPORTS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "reports"))
os.makedirs(REPORTS_DIR, exist_ok=True)


@router.get("/v1/business/stats")
def business_stats():
    """Stats D3Dprintix — connecter Etsy API + n8n pour des vraies données."""
    etsy_key = os.getenv("ETSYPUBLIC_KEY", "")
    listings = 0
    sales    = 0.0
    tasks    = 0
    if etsy_key:
        try:
            import requests as _req
            r = _req.get(
                "https://api.etsy.com/v3/application/listings/active",
                headers={"x-api-key": etsy_key},
                params={"limit": 1},
                timeout=4,
            )
            if r.ok:
                listings = r.json().get("count", 0)
        except Exception:
            pass
    return {"listings": listings, "sales": sales, "tasks": tasks}


@router.post("/v1/reports/generate")
async def generate_report(request: Request):
    import datetime
    body        = await request.json()
    report_type = body.get("type", "system")
    title       = body.get("title", f"JARVIS Report — {report_type.upper()}")
    data        = body.get("data", {})
    notes       = body.get("notes", "")

    now      = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d_%H-%M-%S")
    date_disp= now.strftime("%Y-%m-%d %H:%M")
    filename = f"{date_str}_{report_type}.txt"
    filepath = os.path.join(REPORTS_DIR, filename)

    # Contenu texte brut pour Notepad
    lines = [
        f"{'='*60}",
        f"  JARVIS — {title.upper()}",
        f"  {date_disp}  |  David Arbour",
        f"{'='*60}",
        "",
    ]
    for k, v in data.items():
        lines.append(f"  {k.upper():<20} {v}")
    if notes:
        lines += ["", f"{'─'*60}", "  NOTES", f"{'─'*60}", notes]
    lines += ["", f"{'='*60}", "  GENERATED BY JARVIS · OPENJARVISNEXUS", f"{'='*60}"]

    content = "\n".join(lines)
    with open(filepath, "w", encoding="utf-8") as f:  # NOSONAR - small text report, sync write acceptable
        f.write(content)

    # Destination brain selon le type de rapport (plus OneDrive)
    import shutil

    from config import BRAIN_REPORTS_DIR
    if report_type == "status":
        brain_dir = str(BRAIN_REPORTS_DIR / "status")
    elif report_type == "memory":
        brain_dir = str(BRAIN_REPORTS_DIR / "memory")
    else:
        brain_dir = str(BRAIN_REPORTS_DIR)
    os.makedirs(brain_dir, exist_ok=True)
    brain_path = os.path.join(brain_dir, filename)
    shutil.copy2(filepath, brain_path)
    subprocess.Popen(["notepad.exe", brain_path])  # NOSONAR - fire-and-forget GUI launch

    return {"filename": filename, "filepath": filepath, "title": title}


@router.get("/v1/reports")
def list_reports():
    files = []
    for f in sorted(os.listdir(REPORTS_DIR), reverse=True)[:20]:
        if f.endswith(".txt"):
            files.append({"filename": f, "filepath": os.path.join(REPORTS_DIR, f)})
    return {"reports": files}


@router.get("/v1/sources")
def sources_list():
    return {"sources": []}


@router.get("/v1/logs")
def logs_list():
    return {"logs": []}
