"""Per-pack README.md builder — the buyer's install guide.

Honest about what iOS allows (no 1-click globally) AND sells the time saved.
This file is what makes Etsy reviews 5★ instead of 2★.
"""
from __future__ import annotations

from iconforge.brief import PackBrief

_TEMPLATE = """# {name} — Icon Pack

> **Setup in ~5 minutes** (vs. 1 hour manual). iOS requires one confirmation per
> icon (Apple security — no installer can bypass this), but everything else is
> automated by the included installer Shortcut.

**Pack** : {name} · v{version} · category *{category}* · {count} icons
**Platforms** : {platforms_pretty}
**Theme** : {theme}

## What's in the ZIP

```
{folder_tree}
```

## iOS — quick install (recommended path)

1. **Copy `ios/` to your iCloud Drive** (drag the folder).
2. **Open the included `Install {name}.shortcut`** (Phase 1b — for now use the
   recipe at `shortcut_recipe.json` with your favourite installer like
   *Icon Themer* or *ScriptableIcons*).
3. The installer loops over the {count} icons. For each one iOS will ask
   *"Add to Home Screen?"* — tap **Add**. (~5 sec per icon → ~3 min total.)
4. Move the original apps to **App Library** (long-press → Remove from Home
   Screen → Move to App Library) so only your custom icons show.

> Why one tap per icon? Apple's sandbox does not allow a Shortcut to write to
> the home screen layout without user confirmation. No icon pack on any store
> can bypass this — anyone claiming "1-click install" is misleading.

## Android — Nova Launcher

1. Install **Nova Launcher**.
2. Long-press an app → **Edit** → tap the icon → **Gallery** → pick a PNG from
   the `android/` folder.

## Elgato Stream Deck

1. Open Stream Deck.
2. Drag a PNG from `streamdeck/` onto any button → assign action.

## Files & licence

* `manifest.json` — machine-readable pack metadata (schema `iconforge.pack.v1`)
* `shortcut_recipe.json` — installer recipe (schema `iconforge.installer-recipe.v1`)
* PNGs are yours to use on your devices (single-user licence). No redistribution.

— Generated by Nexus9 IconForge
"""


def _folder_tree(name: str, platforms: list[str], count: int) -> str:
    tree = [f"{name}.zip"]
    for p in platforms:
        tree.append(f"├── {p}/    ({count} PNGs)")
    tree.append("├── manifest.json")
    tree.append("├── shortcut_recipe.json")
    tree.append("└── README.md")
    return "\n".join(tree)


def build_readme(brief: PackBrief, platforms: list[str]) -> str:
    return _TEMPLATE.format(
        name=brief.name,
        version=brief.version,
        category=brief.category,
        theme=brief.theme,
        count=len(brief.icons),
        platforms_pretty=", ".join(platforms),
        folder_tree=_folder_tree(brief.name, platforms, len(brief.icons)),
    )
